In [1]:
import numpy as np

In [2]:
print("Hello World")

Hello World


In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
print("array a : ",a)
print(f"array a : {a}")
print("array a : {}".format(a))

array a :  [1 2 3 4]
array a : [1 2 3 4]
array a : [1 2 3 4]


In [5]:
print(f"ndim:{a.ndim}")

ndim:1


In [6]:
print(f"size:{a.size}")

size:4


In [7]:
print(f"shape:{a.shape}")

shape:(4,)


In [8]:
print(f"dtype:{a.dtype}")

dtype:int32


In [9]:
print(f"itemsize:{a.itemsize}")

itemsize:4


In [10]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b=np.array([1,2,3,4])
c=np.add(a,b)
print(c)

[[ 2  4  6  8]
 [ 6  8 10 12]]


In [13]:
f=np.array([[1,2,3,4],[5,6,7,8]])
c=np.add(a,b)
d=np.subtract(a,b)
e=np.multiply(a,b)
g=np.divide(a,b)
h=np.power(a,b)
i=np.mod(a,b)
j=np.remainder(a,b)
print(c)
print(d)
print(e)
print(g)
print(h)
print(i)
print(j)


[[ 2  4  6  8]
 [ 6  8 10 12]]
[[0 0 0 0]
 [4 4 4 4]]
[[ 1  4  9 16]
 [ 5 12 21 32]]
[[1.         1.         1.         1.        ]
 [5.         3.         2.33333333 2.        ]]
[[   1    4   27  256]
 [   5   36  343 4096]]
[[0 0 0 0]
 [0 0 1 0]]
[[0 0 0 0]
 [0 0 1 0]]


In [18]:
y=np.array(['Aayush','Nixan','Madhvi','Druva','Dyey','Ritik'])
print(y)

['Aayush' 'Nixan' 'Madhvi' 'Druva' 'Dyey' 'Ritik']


In [19]:
z=np.zeros((2,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
one=np.ones((3,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
empty=np.empty((2,2))
print(empty)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]]


In [22]:
ar=np.arange(1,5,0.5)
print(ar)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [23]:
l=np.linspace(1,5,10)
print(l)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [24]:
r=np.random.random((2,3))
print(r)

[[0.19910814 0.45614938 0.70817173]
 [0.96287508 0.94949922 0.06790938]]


In [28]:
a=np.array([[2,3,4],[6,7,8]])
print(a)
sliced_arr=a[:2,:2]
print("Sliced Array:",sliced_arr)

[[2 3 4]
 [6 7 8]]
Sliced Array: [[2 3]
 [6 7]]


In [29]:
indexed_arr=a[[1,0],[0,1]]
print(indexed_arr)

[6 3]


In [30]:
print(a.sum())

30


In [31]:
a1=np.array([25,45,56,81])
print(np.sqrt(a1))

[5.         6.70820393 7.48331477 9.        ]


In [32]:
b=a+5
print(b)

[[ 7  8  9]
 [11 12 13]]


In [33]:
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m2=np.array([[4,5,6],[7,8,9],[4,7,9]])
m3=np.dot(m1,m2)
print(m3)

[[ 30  42  51]
 [ 75 102 123]
 [120 162 195]]


In [34]:
bool=np.array([[True,True,False],[True,False,False]])
print("all() with axis none",np.any(bool))
print("all() with axis=0",np.any(bool,axis=0))
print("all() with axis=1",np.any(bool,axis=1))

all() with axis none True
all() with axis=0 [ True  True False]
all() with axis=1 [ True  True]


In [35]:
bool=np.array([[True,True,False],[True,False,False]])
print("all() with axis none",np.all(bool))
print("all() with axis=0",np.all(bool,axis=0))
print("all() with axis=1",np.all(bool,axis=1))

all() with axis none False
all() with axis=0 [ True False False]
all() with axis=1 [False False]


In [36]:
a1=np.arange(8)
print(a1)
re=a1.reshape(2,4)
print(re)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [37]:
print(m1)
print(m2)
print(m3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]
 [4 7 9]]
[[ 30  42  51]
 [ 75 102 123]
 [120 162 195]]


In [38]:
v=np.vstack((m1,m2,m3))
print(v)

[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [  4   5   6]
 [  7   8   9]
 [  4   7   9]
 [ 30  42  51]
 [ 75 102 123]
 [120 162 195]]


In [39]:
h=np.hstack((m1,m2,m3))
print(h)

[[  1   2   3   4   5   6  30  42  51]
 [  4   5   6   7   8   9  75 102 123]
 [  7   8   9   4   7   9 120 162 195]]


In [41]:
hsplit=np.hsplit(h,3)
print(hsplit)

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[4, 5, 6],
       [7, 8, 9],
       [4, 7, 9]]), array([[ 30,  42,  51],
       [ 75, 102, 123],
       [120, 162, 195]])]


In [42]:
vsplit=np.vsplit(h,3)
print(vsplit)

[array([[ 1,  2,  3,  4,  5,  6, 30, 42, 51]]), array([[  4,   5,   6,   7,   8,   9,  75, 102, 123]]), array([[  7,   8,   9,   4,   7,   9, 120, 162, 195]])]


In [43]:
arr=np.array([23,34,45,67])
print("Sqrt: ",np.sqrt(arr)) #Return the Square root of each element
print("Exp: ",np.exp(arr)) #Return the exponentials each element
print("Sin: ",np.sin(arr)) #Return the sin of each element
print("Cos: ",np.cos(arr)) #Return the cosine of each element
print("Log: ",np.log(arr)) #Return the logarithm of each element
print("Sum: ",np.sum(arr)) #Return the sum total of each element
print("Std: ",np.std(arr)) #Return the standard deviation each element

Sqrt:  [4.79583152 5.83095189 6.70820393 8.18535277]
Exp:  [9.74480345e+09 5.83461743e+14 3.49342711e+19 1.25236317e+29]
Sin:  [-0.8462204   0.52908269  0.85090352 -0.85551998]
Cos:  [-0.53283302 -0.84857027  0.52532199 -0.5177698 ]
Log:  [3.13549422 3.52636052 3.80666249 4.20469262]
Sum:  169
Std:  16.269219403523945


In [44]:
print("Random:{}\n".format(np.random.random(20)));
print("Rand:{}\n".format(np.random.rand(3,4)));
print("Randint:{}\n".format(np.random.randint(0,100,20)));
print("Permutation:{}\n".format(np.random.permutation(np.arange(20))));

Random:[0.03492403 0.00244027 0.90837275 0.3000564  0.67349584 0.44689932
 0.87077301 0.91908789 0.97257374 0.92443932 0.67403475 0.93002514
 0.8670408  0.34582486 0.81277213 0.27294797 0.11708781 0.64926635
 0.62583362 0.34003675]

Rand:[[0.67211724 0.99502412 0.16882539 0.85907899]
 [0.04915309 0.27892814 0.50101757 0.97144285]
 [0.36636956 0.63648595 0.34603914 0.89925226]]

Randint:[ 7 35 72 71 14 91 28  9 46 55 71 90 35  7 79 17 94 80 18 15]

Permutation:[18 16 11  7 19  0 14  1 10 13  9  6  2  8  5  3 17 12 15  4]

